title: Open Coding Society 
description: "Class of 2026"
owner_name: Aditya Katre
github_username: adik1025
github_repo: "student_2026" 
baseurl: "/student_2026"
future: true

remote_theme: jekyll/minima
# remote_theme: pages-themes/minimal@v0.2.0


minima:
  nav_pages:
    - navigation/lessons.md
    - navigation/blog.md
    - navigation/github-pages-readme.md
    - navigation/leaderboard.md
    - navigation/checklist.md
    - navigation/authentication/login.md
    - navigation/authentication/logout.md


  skin: dark
  social_links:
    - { platform: github, user_url: "https://github.com/Open-Coding-Society"}
    - { platform: x, user_url: "https://x.com/Open_Coding" }
    - { platform: youtube, user_url: "https://www.youtube.com/@OpenCodingSociety" } 

plugins:
  - jekyll-remote-theme